### ISSUE TITLE
Move to gh-pages branch

### ISSUE THREAD

**Issue by konklone** [sbma44/arduino_class#1]
And add permalinks to the PDFs in the README. (I'd do a PR, but I don't think GitHub allows you to propose merging into a non-existent branch.)

**Comment by sbma44** [comment]
I added links to the README that point to the Google presentation permalinks, because I think the experience is superior to the PDFs. I'm not sure what other gh-pages kookiness you might prefer, though, so let me know! I did go ahead and create a gh-pages branch just for the hell/permalinkability of it.

**Comment by konklone** [comment]
Oh, sure, links to the GDocs work too. :+1:
